apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
- path: gateway.yaml
  target:
    kind: Gateway
labels:
- pairs:
    app.kubernetes.io/instance: wide-ep
    app.kubernetes.io/gateway: wide-ep-inference-gateway
    app.kubernetes.io/component: inference-gateway
